name: Deploy SVPP Website

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Deploy to GitHub Pages directly
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
